# .github/workflows/spotify-tracker.yml
name: Spotify Playlist Tracker

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  check-playlist-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run playlist tracker
        run: node src/playlist-tracker.js
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      # Commit updated songs.json and metadata.json
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'data/songs.json data/metadata.json data/playlists.json'
          message: 'Update playlist data [skip ci]'
          default_author: github_actions
          github_token: ${{ secrets.GITHUB_TOKEN }}
